log:
  level: DEBUG
serversTransport:
  insecureSkipVerify: true
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: web-secure
          scheme: https
  web-secure:
    address: :443
api:
  dashboard: true
  insecure: false
providers:
  docker:
    exposedByDefault: false